# Generated by Django 3.2.6 on 2021-09-01 02:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=100)),
                ('target', models.TextField()),
                ('created_date', models.DateField(default=datetime.date.today)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.PositiveIntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('habit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.habit')),
            ],
        ),
        migrations.AddConstraint(
            model_name='dailyresults',
            constraint=models.UniqueConstraint(fields=('habit', 'date'), name='daily_record'),
        ),
    ]
