# Generated by Django 3.2.6 on 2021-09-01 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210901_0238'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyResults',
            new_name='DailyResult',
        ),
    ]
