# Generated by Django 3.2.6 on 2021-09-03 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_dailyresults_dailyresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='target',
        ),
    ]
